"""SpiceTrellis public API."""

from spicetrellis._version import __version__
from spicetrellis.api import (
    IR_SCHEMA,
    IR_VERSION,
    AnalysisLimits,
    CircuitIR,
    CircuitIRError,
    ElaborationLimits,
    IRInstance,
    IRLoss,
    IRModel,
    IRModule,
    IRParameter,
    IRSource,
    analyze_file,
    build_ir,
    dump_ir,
    flatten,
    format_deck,
    fuzz_smoke,
    inventory,
    load_ir,
    load_ir_text,
    parse_text,
    structural_summary,
    validate_ir,
    write_ir,
)

__all__ = [
    "IR_SCHEMA",
    "IR_VERSION",
    "AnalysisLimits",
    "CircuitIR",
    "CircuitIRError",
    "ElaborationLimits",
    "IRInstance",
    "IRLoss",
    "IRModel",
    "IRModule",
    "IRParameter",
    "IRSource",
    "__version__",
    "analyze_file",
    "build_ir",
    "dump_ir",
    "flatten",
    "format_deck",
    "fuzz_smoke",
    "inventory",
    "load_ir",
    "load_ir_text",
    "parse_text",
    "structural_summary",
    "validate_ir",
    "write_ir",
]
